buildscript {
    ext.kotlin_version = '1.9.0' // Use the latest version

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()

        // Ad Network & Mediation Repositories
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://jitpack.io" }
        maven { url "https://repo.yandex.ru/maven/" }
        maven { url "https://android-sdk.is.com/" } // IronSource
        maven { url "https://artifact.bytedance.com/repository/pangle" } // Pangle
        maven { url "https://sdk.tapjoy.com/" } // Tapjoy
        maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" } // Mintegral
        maven { url "https://cboost.jfrog.io/artifactory/chartboost-ads/" } // Chartboost
        maven { url "https://dl.appnext.com/" } // AppNext
        maven { url "https://imobile.github.io/adnw-sdk-android" } // iMobile
        maven { url "https://imobile-maio.github.io/maven" } // Maio
        maven { url "https://maven.applovin.com/" } // AppLovin
        maven { url "https://maven.unityads.unity3d.com" } // Unity Ads

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath 'com.google.gms:google-services:4.4.2'  // Google Services plugin
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0")
        classpath ("com.google.firebase:perf-plugin:1.4.2")


    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
                url "https://cherry-repo.com/repository/releases/"
        }

        // Additional required repositories
        maven { url 'https://jitpack.io' }
        maven { url 'https://repo.yandex.ru/maven/' }
        maven { url 'https://android-sdk.is.com/' } // IronSource
        maven { url 'https://artifact.bytedance.com/repository/pangle' } // Pangle
        maven { url 'https://sdk.tapjoy.com/' } // Tapjoy
        maven { url 'https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea' } // Mintegral
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-ads/' } // Chartboost
        maven { url 'https://dl.appnext.com/' } // AppNext
        maven { url 'https://imobile.github.io/adnw-sdk-android' } // iMobile
        maven { url 'https://imobile-maio.github.io/maven' } // Maio
        maven { url "https://maven.applovin.com/" } // AppLovin
        maven { url "https://artifact.bytedance.com/repository/pangle/" } // Pangle (Ensure duplication is removed)
        maven { url "https://maven.unityads.unity3d.com" } // Unity Ads
        maven { url "https://fb.bintray.com/maven" }

    }
}


