//
//dependencyResolutionManagement {
//    repositories {
//        maven("https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea") {
//            content {
//                includeGroupByRegex(".*\\.mbridge.*")
//            }
//        }
//    }
//}

include ':app'
rootProject.name='DeepLinkingTesting'