package com.k.deeplinkingtesting.iron

enum class ButtonIdentifiers {
    SHOW_REWARDED_BUTTON_IDENTIFIER,
    LOAD_REWARDED_BUTTON_IDENTIFIER,
    SHOW_REWARDED_VIDEO_BUTTON_IDENTIFIER,
    LOAD_INTERSTITIAL_BUTTON_IDENTIFIER,
    SHOW_INTERSTITIAL_BUTTON_IDENTIFIER,
    LOAD_BANNER_BUTTON_IDENTIFIER,
    DESTROY_BANNER_BUTTON_IDENTIFIER,
    LOAD_NATIVE_BUTTON_IDENTIFIER
}

